# state/graph_state.py
# This module defines the GraphState dataclass.
# In a multi-agent or workflow-based system, we need a single shared object that represents
# the state of the conversation and the outputs of the intermediate agent runs.
# The orchestrator starts with an initial GraphState, passes it to the Supervisor, Search Agent, and
# Summary Agent, each of which reads from and writes their outputs back to this state object.

from dataclasses import dataclass, field
from typing import Dict, List, Optional

from app.models.chat_models import ChatMessage, SearchResult

# @dataclass automatically generates standard class methods like __init__ and __repr__ for us.
@dataclass
class GraphState:
    """
    GraphState holds the runtime data for a single user interaction cycle.
    As it passes through different steps/agents, its fields are populated.
    """
    conversation_id: str                      # Unique identifier for the conversation session
    user_message: str                         # The text query the user just sent
    history: List[ChatMessage]                # Request chat history as ChatMessage models
    # conversation_context holds historical context as dictionaries.
    # field(default_factory=list) ensures that each instance gets its own new list [] rather than sharing a single list in memory.
    conversation_context: List[Dict[str, str]] = field(default_factory=list)
    
    route: str = "summary"                    # Selected routing path: "greeting", "search", "summary", or "parallel"
    summary_output: str = ""                  # Output generated by the SummaryAgent
    search_output: str = ""                   # Output text generated by the SearchAgent (e.g. formatted elasticsearch hits)
    search_results: Optional[List[SearchResult]] = None  # Raw search hits retrieved from the Elasticsearch database
    final_answer: str = ""                    # The final combined/grounded response returned to the user